//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IslamicGuide.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AyaWord
    {
        public Nullable<int> SoraID { get; set; }
        public Nullable<int> AyaNum { get; set; }
        public Nullable<int> AyaID { get; set; }
        public string AyaWords { get; set; }
        public string AyaWordsUnDiac { get; set; }
        public string AyaWordsEn { get; set; }
        public string AyaStems { get; set; }
        public int p_Id { get; set; }
    }
}
