//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IslamicGuide.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Position()
        {
            this.MapSubjectsQurans = new HashSet<MapSubjectsQuran>();
            this.MapBookQurans = new HashSet<MapBookQuran>();
        }
    
        public int ID { get; set; }
        public Nullable<int> FromQuranWordID { get; set; }
        public Nullable<int> ToQuranWordID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MapSubjectsQuran> MapSubjectsQurans { get; set; }
        public virtual QuranWord QuranWord { get; set; }
        public virtual QuranWord QuranWord1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MapBookQuran> MapBookQurans { get; set; }
    }
}
