//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IslamicGuide.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PraysTime
    {
        public int Id { get; set; }
        public string Name_English { get; set; }
        public string Name_Arabic { get; set; }
        public string Time { get; set; }
    }
}
