//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LayoutResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LayoutResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("temp.Resources.LayoutResource", typeof(LayoutResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribed successfully.
        /// </summary>
        public static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al-Fatiha.
        /// </summary>
        public static string AlFatiha {
            get {
                return ResourceManager.GetString("AlFatiha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the name of God, the Gracious, the Merciful (1) Praise be to God, Lord of the Worlds (2) The Most Gracious, the Most Merciful (3) Master of the Day of Judgment (4) It is You we worship, and upon You we call for help (5) Guide us to the straight path (6) The path of those You have blessed, not of those against whom there is anger, nor of those who are misguided (7).
        /// </summary>
        public static string AlFatiha_sora {
            get {
                return ResourceManager.GetString("AlFatiha_sora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide us to the straight path.
        /// </summary>
        public static string AlFatihaverse6 {
            get {
                return ResourceManager.GetString("AlFatihaverse6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide us to the straight path.The way of those on whom You have granted Your grace, not (the way) of those who earned Your anger, nor of those who went astray, Allah says, `This is for My servant, and My servant shall acquire what he asked for..
        /// </summary>
        public static string Alfatihaverse6tafsir {
            get {
                return ResourceManager.GetString("Alfatihaverse6tafsir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then Allah said :.
        /// </summary>
        public static string Allahsaid {
            get {
                return ResourceManager.GetString("Allahsaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asar.
        /// </summary>
        public static string Asar {
            get {
                return ResourceManager.GetString("Asar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asbab Al-Nuzul.
        /// </summary>
        public static string AsbabAlNuzul {
            get {
                return ResourceManager.GetString("AsbabAlNuzul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayat.
        /// </summary>
        public static string Ayat {
            get {
                return ResourceManager.GetString("Ayat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book1.
        /// </summary>
        public static string Book1 {
            get {
                return ResourceManager.GetString("Book1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright© 2019. All Rights Reserved.
        /// </summary>
        public static string Copyrights {
            get {
                return ResourceManager.GetString("Copyrights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dhur.
        /// </summary>
        public static string Dhur {
            get {
                return ResourceManager.GetString("Dhur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Added Successfully.
        /// </summary>
        public static string EmailAdded {
            get {
                return ResourceManager.GetString("EmailAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something Wrong Happened, Please Try Again.
        /// </summary>
        public static string EmailWrong {
            get {
                return ResourceManager.GetString("EmailWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Email.
        /// </summary>
        public static string Entermail {
            get {
                return ResourceManager.GetString("Entermail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fajr.
        /// </summary>
        public static string Fajr {
            get {
                return ResourceManager.GetString("Fajr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fasting.
        /// </summary>
        public static string Fasting {
            get {
                return ResourceManager.GetString("Fasting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get in touch.
        /// </summary>
        public static string Getintouch {
            get {
                return ResourceManager.GetString("Getintouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hajj.
        /// </summary>
        public static string Hajj {
            get {
                return ResourceManager.GetString("Hajj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hedayt Alayat.
        /// </summary>
        public static string Hedayt_Alayat {
            get {
                return ResourceManager.GetString("Hedayt_Alayat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tafsir Ibn Kasir.
        /// </summary>
        public static string IbnKasir {
            get {
                return ResourceManager.GetString("IbnKasir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isha.
        /// </summary>
        public static string Isha {
            get {
                return ResourceManager.GetString("Isha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Islamic Pillars.
        /// </summary>
        public static string IslamicPillar {
            get {
                return ResourceManager.GetString("IslamicPillar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khotba.
        /// </summary>
        public static string Khotba {
            get {
                return ResourceManager.GetString("Khotba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to link1.
        /// </summary>
        public static string link1 {
            get {
                return ResourceManager.GetString("link1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to link2.
        /// </summary>
        public static string link2 {
            get {
                return ResourceManager.GetString("link2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to link3.
        /// </summary>
        public static string link3 {
            get {
                return ResourceManager.GetString("link3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to link4.
        /// </summary>
        public static string link4 {
            get {
                return ResourceManager.GetString("link4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to link5.
        /// </summary>
        public static string link5 {
            get {
                return ResourceManager.GetString("link5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to link6.
        /// </summary>
        public static string link6 {
            get {
                return ResourceManager.GetString("link6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to link7.
        /// </summary>
        public static string link7 {
            get {
                return ResourceManager.GetString("link7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magrib.
        /// </summary>
        public static string Magrib {
            get {
                return ResourceManager.GetString("Magrib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter sign up.
        /// </summary>
        public static string Newsletter {
            get {
                return ResourceManager.GetString("Newsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Latest Updates.
        /// </summary>
        public static string Newsletterupdate {
            get {
                return ResourceManager.GetString("Newsletterupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Subject has no Positions.
        /// </summary>
        public static string NoPositions {
            get {
                return ResourceManager.GetString("NoPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no results found.
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pillars of Islam.
        /// </summary>
        public static string Pillars {
            get {
                return ResourceManager.GetString("Pillars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position1.
        /// </summary>
        public static string Position1 {
            get {
                return ResourceManager.GetString("Position1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positions.
        /// </summary>
        public static string Positions {
            get {
                return ResourceManager.GetString("Positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quran.
        /// </summary>
        public static string Quran {
            get {
                return ResourceManager.GetString("Quran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading principles.
        /// </summary>
        public static string Readingprinciples {
            get {
                return ResourceManager.GetString("Readingprinciples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readings.
        /// </summary>
        public static string Readings {
            get {
                return ResourceManager.GetString("Readings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more.
        /// </summary>
        public static string Readmore {
            get {
                return ResourceManager.GetString("Readmore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salah.
        /// </summary>
        public static string Salah {
            get {
                return ResourceManager.GetString("Salah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your keyword.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Searchkeyword {
            get {
                return ResourceManager.GetString("Searchkeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shahdah.
        /// </summary>
        public static string Shahdah {
            get {
                return ResourceManager.GetString("Shahdah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more.
        /// </summary>
        public static string Showmore {
            get {
                return ResourceManager.GetString("Showmore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject1.
        /// </summary>
        public static string Subject1 {
            get {
                return ResourceManager.GetString("Subject1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subjects.
        /// </summary>
        public static string Subjects {
            get {
                return ResourceManager.GetString("Subjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit now.
        /// </summary>
        public static string Submitnow {
            get {
                return ResourceManager.GetString("Submitnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tafsirs.
        /// </summary>
        public static string Tafsir {
            get {
                return ResourceManager.GetString("Tafsir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tajweeds.
        /// </summary>
        public static string Tajweed {
            get {
                return ResourceManager.GetString("Tajweed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tajweed Princples.
        /// </summary>
        public static string TajweedPrincples {
            get {
                return ResourceManager.GetString("TajweedPrincples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations.
        /// </summary>
        public static string Targmat {
            get {
                return ResourceManager.GetString("Targmat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readings.
        /// </summary>
        public static string Tlawa {
            get {
                return ResourceManager.GetString("Tlawa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topics.
        /// </summary>
        public static string Topics {
            get {
                return ResourceManager.GetString("Topics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Meanings.
        /// </summary>
        public static string WordMeanings {
            get {
                return ResourceManager.GetString("WordMeanings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong happened Try again later.
        /// </summary>
        public static string Wrong {
            get {
                return ResourceManager.GetString("Wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email.
        /// </summary>
        public static string Yemail {
            get {
                return ResourceManager.GetString("Yemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Message.
        /// </summary>
        public static string Ymessage {
            get {
                return ResourceManager.GetString("Ymessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Mobile.
        /// </summary>
        public static string yMobile {
            get {
                return ResourceManager.GetString("yMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        public static string Yname {
            get {
                return ResourceManager.GetString("Yname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakat.
        /// </summary>
        public static string Zakat {
            get {
                return ResourceManager.GetString("Zakat", resourceCulture);
            }
        }
    }
}
