//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace temp
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuranAyat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuranAyat()
        {
            this.BookContents = new HashSet<BookContent>();
            this.QuranWords = new HashSet<QuranWord>();
        }
    
        public int ID { get; set; }
        public string Aya { get; set; }
        public Nullable<int> SoraID { get; set; }
        public Nullable<int> AyaNum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookContent> BookContents { get; set; }
        public virtual QuranSuar QuranSuar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuranWord> QuranWords { get; set; }
    }
}
