//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace temp
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuranWord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuranWord()
        {
            this.Positions = new HashSet<Position>();
            this.Positions1 = new HashSet<Position>();
        }
    
        public int ID { get; set; }
        public string Word { get; set; }
        public string WordUnDiac { get; set; }
        public string Stem { get; set; }
        public Nullable<int> AyaID { get; set; }
        public Nullable<int> SoraID { get; set; }
        public Nullable<int> AyaNum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Position> Positions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Position> Positions1 { get; set; }
        public virtual QuranAyat QuranAyat { get; set; }
        public virtual QuranSuar QuranSuar { get; set; }
    }
}
